/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/addresses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_accounts_addresses_list"];
        put?: never;
        post: operations["v1_accounts_addresses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/addresses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_accounts_addresses_retrieve"];
        put: operations["v1_accounts_addresses_update"];
        post?: never;
        delete: operations["v1_accounts_addresses_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_accounts_addresses_partial_update"];
        trace?: never;
    };
    "/api/v1/accounts/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_accounts_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_accounts_me_update_partial_update"];
        trace?: never;
    };
    "/api/v1/accounts/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_accounts_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/blacklist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and blacklists it. Must be used with the
         *     `rest_framework_simplejwt.token_blacklist` app installed.
         */
        post: operations["v1_auth_token_blacklist_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["v1_auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_catalog_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_catalog_categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_catalog_products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_catalog_products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{slug}/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_catalog_products_reviews_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            readonly id: number;
            /** @description Ev, İş, Tatil... */
            label: string;
            name: string;
            phone: string;
            line: string;
            district?: string;
            city: string;
            postal_code?: string;
            country?: string;
            is_default?: boolean;
        };
        AddressRequest: {
            /** @description Ev, İş, Tatil... */
            label: string;
            name: string;
            phone: string;
            line: string;
            district?: string;
            city: string;
            postal_code?: string;
            country?: string;
            is_default?: boolean;
        };
        Category: {
            readonly id: number;
            slug: string;
            name: string;
            description?: string;
            parent?: number | null;
            /** Format: uri */
            image_url?: string;
            /** Format: int64 */
            sort_order?: number;
            is_visible?: boolean;
            readonly count: number;
        };
        /** @description JWT response içine kullanıcı bilgisi ekle. */
        EkimTokenRequest: {
            email: string;
            password: string;
        };
        PaginatedAddressList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Address"][];
        };
        PaginatedProductListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductList"][];
        };
        PatchedAddressRequest: {
            /** @description Ev, İş, Tatil... */
            label?: string;
            name?: string;
            phone?: string;
            line?: string;
            district?: string;
            city?: string;
            postal_code?: string;
            country?: string;
            is_default?: boolean;
        };
        /** @description Ürün detay ekranı için tam sürüm. */
        ProductDetail: {
            readonly id: number;
            slug: string;
            name: string;
            category: number;
            readonly category_slug: string;
            sku?: string;
            artisan?: string;
            artisan_city?: string;
            currency?: string;
            /** Format: decimal */
            price: string;
            /** Format: decimal */
            old_price?: string | null;
            description?: string;
            materials?: unknown;
            care?: string;
            /** @description örn. 3-5 gün */
            lead_time?: string;
            tags?: unknown;
            customizable?: boolean;
            size_type?: components["schemas"]["SizeTypeEnum"];
            /** Format: decimal */
            rating?: string;
            /** Format: int64 */
            review_count?: number;
            readonly total_stock: number;
            readonly in_stock: boolean;
            readonly images: components["schemas"]["ProductImage"][];
            readonly variants: components["schemas"]["ProductVariant"][];
            seo_title?: string;
            seo_description?: string;
        };
        ProductImage: {
            readonly id: number;
            readonly image: string;
            alt?: string;
            /** Format: int64 */
            sort_order?: number;
            is_cover?: boolean;
        };
        /** @description Liste ekranları için hafif sürüm. */
        ProductList: {
            readonly id: number;
            slug: string;
            name: string;
            category: number;
            readonly category_slug: string;
            artisan?: string;
            artisan_city?: string;
            currency?: string;
            /** Format: decimal */
            price: string;
            /** Format: decimal */
            old_price?: string | null;
            /** Format: decimal */
            rating?: string;
            /** Format: int64 */
            review_count?: number;
            tags?: unknown;
            customizable?: boolean;
            size_type?: components["schemas"]["SizeTypeEnum"];
            readonly cover_image: string;
            is_visible?: boolean;
        };
        ProductVariant: {
            readonly id: number;
            size_label?: string;
            color_name?: string;
            color_hex?: string;
            sku?: string;
            /** Format: int64 */
            stock?: number;
            /** Format: decimal */
            price_delta?: string;
            is_active?: boolean;
        };
        Register: {
            /**
             * E-posta
             * Format: email
             */
            email: string;
            /** Adı */
            first_name?: string;
            /** Soyadı */
            last_name?: string;
            phone?: string;
            marketing_opt_in?: boolean;
        };
        RegisterRequest: {
            /**
             * E-posta
             * Format: email
             */
            email: string;
            /** Adı */
            first_name?: string;
            /** Soyadı */
            last_name?: string;
            phone?: string;
            password: string;
            marketing_opt_in?: boolean;
        };
        /**
         * @description * `one-size` - Tek beden
         *     * `apparel` - Tekstil bedeni
         *     * `numeric-cm` - Santim ölçü
         *     * `paper` - Kağıt ebadı
         * @enum {string}
         */
        SizeTypeEnum: "one-size" | "apparel" | "numeric-cm" | "paper";
        TokenBlacklistRequest: {
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_accounts_addresses_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAddressList"];
                };
            };
        };
    };
    v1_accounts_addresses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AddressRequest"];
                "multipart/form-data": components["schemas"]["AddressRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
        };
    };
    v1_accounts_addresses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
        };
    };
    v1_accounts_addresses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AddressRequest"];
                "multipart/form-data": components["schemas"]["AddressRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
        };
    };
    v1_accounts_addresses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_accounts_addresses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAddressRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAddressRequest"];
                "multipart/form-data": components["schemas"]["PatchedAddressRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
        };
    };
    v1_accounts_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_accounts_me_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_accounts_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EkimTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EkimTokenRequest"];
                "multipart/form-data": components["schemas"]["EkimTokenRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_blacklist_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBlacklistRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenBlacklistRequest"];
                "multipart/form-data": components["schemas"]["TokenBlacklistRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_catalog_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    v1_catalog_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_catalog_products_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductListList"];
                };
            };
        };
    };
    v1_catalog_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
        };
    };
    v1_catalog_products_reviews_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
        };
    };
}
