# Generated by Django 5.2.13 on 2026-04-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=60)),
                ('channel', models.CharField(choices=[('email', 'E-posta'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesaj şablonu',
                'verbose_name_plural': 'Mesaj şablonları',
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='unique_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_staff', models.BooleanField(db_index=True, default=False)),
                ('kind', models.CharField(choices=[('order', 'Sipariş'), ('stock', 'Stok'), ('review', 'Yorum'), ('return', 'İade'), ('delivery', 'Teslimat'), ('customer', 'Müşteri'), ('payment', 'Ödeme'), ('system', 'Sistem')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=16)),
                ('to_address', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Kuyruğa alındı'), ('sent', 'Gönderildi'), ('delivered', 'Teslim'), ('failed', 'Başarısız')], default='queued', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.messagetemplate')),
            ],
            options={
                'verbose_name': 'Giden mesaj',
                'verbose_name_plural': 'Giden mesajlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
