# Generated by Django 5.2.13 on 2026-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactmessage_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Yatay kampanya görseli — önerilen ~1600x500 (masaüstü şerit)",
                        upload_to="banners/",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="Dar ekran görseli — önerilen ~1200x600 (2:1). Boş bırakılırsa masaüstü görseli kırpılarak kullanılır ve kenardaki yazılar kesilebilir.",
                        null=True,
                        upload_to="banners/",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Erişilebilirlik/alt metni; görselin üzerine yazılmaz",
                        max_length=140,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Tıklanınca gidilecek yol, ör. /kategori/oyuncak",
                        max_length=300,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ana sayfa banner",
                "verbose_name_plural": "Ana sayfa bannerları",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
