# Generated by Django 5.2.13 on 2026-04-20 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        db_index=True, help_text="IAD-20250421-0001", max_length=24, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("received", "Teslim alındı"),
                            ("refunded", "İade edildi"),
                            ("cancelled", "İptal"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("refund", "Para iadesi"),
                            ("exchange", "Değişim"),
                            ("store_credit", "Mağaza kredisi"),
                        ],
                        default="refund",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_item", "Yanlış ürün gönderildi"),
                            ("damaged", "Hasarlı/kusurlu"),
                            ("not_as_described", "Açıklamayla uyuşmuyor"),
                            ("size", "Beden/ölçü uygun değil"),
                            ("changed_mind", "Vazgeçtim"),
                            ("other", "Diğer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("customer_note", models.TextField(blank=True, help_text="Müşterinin açıklaması")),
                ("admin_note", models.TextField(blank=True, help_text="Yalnızca yönetime görünür")),
                ("refund_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("return_shipping_label", models.URLField(blank=True, help_text="Kargo etiketi PDF URL'si")),
                ("tracking_number", models.CharField(blank=True, max_length=80)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="returns", to="orders.order"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "İade talebi",
                "verbose_name_plural": "İade talepleri",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Talep anındaki birim fiyat", max_digits=10
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade satırı",
                "verbose_name_plural": "İade satırları",
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["status", "-created_at"], name="orders_retu_status_3b5dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["user", "-created_at"], name="orders_retu_user_id_6e7e2c_idx"),
        ),
    ]
