# Generated by Django 5.2.13 on 2026-04-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, help_text="Varyant yoksa kullanılır"),
        ),
    ]
