# Generated by Django 5.2.13 on 2026-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_to_order',
            field=models.BooleanField(default=True, help_text='Siparişle üretilir: stok sınırı uygulanmaz. Tek üretim/sınırlı ürünlerde kapatıp stok girin.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text="Varyant yoksa ve 'siparişle üretilir' kapalıysa kullanılır"),
        ),
    ]
