# Generated by Django 5.2.13 on 2026-04-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Ev, İş, Tatil...', max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('line', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='TR', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_order', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_order', models.BooleanField(default=True)),
                ('sms_marketing', models.BooleanField(default=False)),
                ('push_order', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim tercihi',
                'verbose_name_plural': 'Bildirim tercihleri',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iyzico_card_token', models.CharField(blank=True, max_length=128)),
                ('card_alias', models.CharField(blank=True, max_length=60)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödeme yöntemi',
                'verbose_name_plural': 'Ödeme yöntemleri',
            },
        ),
    ]
