# Generated by Django 5.2.13 on 2026-04-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_enc', models.CharField(blank=True, max_length=255)),
                ('api_username', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Kargo sağlayıcı',
                'verbose_name_plural': 'Kargo sağlayıcılar',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Talep edildi'), ('approved', 'Onaylandı'), ('received', 'Alındı'), ('refunded', 'İade edildi'), ('rejected', 'Reddedildi')], default='requested', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'İade talebi',
                'verbose_name_plural': 'İade talepleri',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(max_length=60, unique=True)),
                ('label_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Oluşturuldu'), ('labeled', 'Etiket basıldı'), ('picked_up', 'Toplandı'), ('in_transit', 'Dağıtımda'), ('delivered', 'Teslim'), ('returned', 'İade'), ('failed', 'Başarısız')], default='created', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('raw_events', models.JSONField(blank=True, default=list)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingprovider')),
            ],
            options={
                'verbose_name': 'Gönderi',
                'verbose_name_plural': 'Gönderiler',
                'ordering': ('-created_at',),
            },
        ),
    ]
