# Generated by Django 5.2.13 on 2026-04-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='iyzico', max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('authorized', 'Yetkilendi'), ('captured', 'Tahsil edildi'), ('failed', 'Başarısız'), ('canceled', 'İptal'), ('refunded', 'İade')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('installment', models.PositiveSmallIntegerField(default=1)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ödeme girişimi',
                'verbose_name_plural': 'Ödeme girişimleri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymentintent')),
            ],
            options={
                'verbose_name': 'İade',
                'verbose_name_plural': 'İadeler',
            },
        ),
    ]
