# Generated by Django 5.2.13 on 2026-04-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('layers', models.JSONField(blank=True, default=list, help_text='Katman listesi (type, x, y, rotation, src...)')),
                ('canvas_size', models.JSONField(blank=True, default=dict)),
                ('preview_url', models.URLField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasarım taslağı',
                'verbose_name_plural': 'Tasarım taslakları',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonalizationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Görsel'), ('text', 'Metin'), ('svg', 'Vektör')], max_length=16)),
                ('file', models.FileField(blank=True, upload_to='personalization/%Y/%m/')),
                ('text_content', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalization_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Kişiselleştirme asset'i",
                'verbose_name_plural': "Kişiselleştirme asset'leri",
            },
        ),
    ]
